(require-library extras ports data-structures srfi-13 files)
(require-extension loops scsh-process args regex)
(import (only extras printf))
(import (only ports with-output-to-port))
(import (only data-structures alist-ref string-split))
(use posix)
(use args)
(use loops)
(use scsh-process)
(include "include/util.scm")
(include "include/init.scm")
(include "include/options.scm")
(include "include/git.scm")

(receive (options operands)
    (args:parse (command-line-arguments) cli-opts) "")
