(require-library extras ports data-structures srfi-13 files)
(import (only extras printf))
(import (only ports with-output-to-port))
(import (only data-structures alist-ref string-split))
(use posix)
(use args)
(use loops)
(use scsh-process)
(include "include/options.scm")
(include "include/git.scm")

(define (usage)
  (with-output-to-port (current-error-port)
    (lambda ()
      (print "Usage: " (car (argv)) " [options...] [files...]")
      (newline)
      (print (args:usage cli-opts))))
  (exit 1))

(receive (options operands)
    (args:parse (command-line-arguments) cli-opts) "")
